name: Black Code Formatter Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use a specific Python version (e.g., '3.11') or '3.x'
          cache: "pip"

      - name: Install Black
        run: pip install black

      - name: Run Black check
        # The --check flag prevents Black from making changes and only exits with an error if formatting is needed.
        # The --diff flag shows the differences.
        run: black --check --diff .
