name: Build and Deploy Documentation

# Run workflow on push to main branch and when manually triggered.
on:
  push:
    branches:
      - main
    tags:
      - "*" # Optional: also trigger on new tags
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual runs from GitHub UI

# Restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Build Sphinx documentation
        run: |
          uv run sphinx-build -b html docs/source docs/build/html

      - name: Upload documentation artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  # Deploy the artifact to GitHub Pages.
  deploy:
    # Only deploy on pushes to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build # Deploy only after the 'build' job succeeds
    runs-on: ubuntu-latest
    permissions:
      pages: write # Grant permission to write to GitHub Pages
      id-token: write # Required to authenticate with GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
